import json
import logging
from typing import List, Optional
from pydantic import BaseModel, Field
from pydantic_ai import Agent
from pydantic_ai.providers.anthropic import AnthropicProvider
from pydantic_ai.models.anthropic import AnthropicModel
from src.clinical_analyst.config import settings
from .fhir_validator import ValidationReport

logger = logging.getLogger(__name__)


class ValidationDecision(BaseModel):
    """Decision and feedback generated by the Validator Agent."""

    accepted: bool = Field(
        description="True if the extracted bundle is perfect, False if corrections are needed."
    )
    feedback: str = Field(
        description="Detailed instructions on what the Extractor Agent missed or got wrong (based on the note and Pydantic errors). Empty if accepted."
    )


class ValidatorAgent:
    """Phase 5 AC2: A secondary agent that acts as a supervisor over the extraction pipeline."""

    def __init__(self):
        if not settings.ANTHROPIC_API_KEY:
            raise ValueError(
                "ANTHROPIC_API_KEY must be set in .env to use the Validator Agent."
            )

        provider = AnthropicProvider(api_key=settings.ANTHROPIC_API_KEY)
        self.model = AnthropicModel("claude-sonnet-4-6", provider=provider)

        self.agent = Agent(
            self.model,
            output_type=ValidationDecision,
            system_prompt=(
                "You are the FHIR Validator Supervisor Agent. Your job is to enforce extreme accuracy and completeness in EHR-to-FHIR extraction.\n"
                "You will receive:\n"
                "1. The original clinical note.\n"
                "2. The extracted FHIR bundle generated by an Extractor Agent.\n"
                "3. A Python validation report showing which resources passed/failed strict HL7 FHIR schema rules.\n\n"
                "If the extraction completely captures the note and has zero INVALID objects, return `accepted=True`.\n"
                "If anything is missing, hallucinatory, or marked INVALID, return `accepted=False` and provide explicit, step-by-step `feedback` instructing the Extractor on how to fix it."
            ),
        )

    async def evaluate_bundle(
        self,
        note: str,
        extractor_messages: list,
        validation_reports: List[ValidationReport],
    ) -> ValidationDecision:
        """Phase 5 AC3: Consumes the context and generates a structured decision."""

        # Format the Pydantic validation status for the LLM prompt
        report_summary = []
        for i, report in enumerate(validation_reports):
            status = report.status
            res_type = report.raw_dict.get("resourceType", "Unknown")
            errors = ", ".join(report.errors) if report.errors else "None"

            block = f"Resource {i + 1} [{res_type}]: STATUS={status}\nErrors: {errors}\nRaw Data: {json.dumps(report.raw_dict, indent=2)}\n"
            report_summary.append(block)

        compiled_report = "\n".join(report_summary)

        prompt = (
            f"--- ORIGINAL CLINICAL NOTE ---\n{note}\n\n"
            f"--- PYTHON VALIDATION REPORT ---\n"
            f"The Extractor generated {len(validation_reports)} resources. Here is their evaluation against strict fhir.resources Python models:\n"
            f"{compiled_report}\n\n"
            "Review this output against the clinical note. Did they miss anything? Do they need to fix schema errors? Make your decision."
        )

        try:
            logger.info("Validator Agent evaluating bundle...")
            result = await self.agent.run(prompt)
            return result.output
        except Exception as e:
            logger.error(f"Validator Agent failed: {e}")
            # Failsafe: if the validator crashes, reject with a generic error
            return ValidationDecision(
                accepted=False,
                feedback=f"Validator Agent encountered a critical error: {e}",
            )
