import logging
from typing import List, Dict, Any, Optional
from pydantic import ValidationError, BaseModel

# Phase 6: All 55 Clinical and Base FHIR R4 Resources
# Clinical - Summary
from fhir.resources.adverseevent import AdverseEvent
from fhir.resources.allergyintolerance import AllergyIntolerance
from fhir.resources.clinicalimpression import ClinicalImpression
from fhir.resources.condition import Condition
from fhir.resources.detectedissue import DetectedIssue
from fhir.resources.familymemberhistory import FamilyMemberHistory
from fhir.resources.procedure import Procedure

# Clinical - Diagnostics
from fhir.resources.bodystructure import BodyStructure
from fhir.resources.diagnosticreport import DiagnosticReport
from fhir.resources.imagingstudy import ImagingStudy

# Note: Media resource not available in fhir.resources R4 (deprecated or merged)
from fhir.resources.molecularsequence import MolecularSequence
from fhir.resources.observation import Observation
from fhir.resources.questionnaireresponse import QuestionnaireResponse
from fhir.resources.specimen import Specimen

# Clinical - Medications
from fhir.resources.immunization import Immunization
from fhir.resources.immunizationevaluation import ImmunizationEvaluation
from fhir.resources.immunizationrecommendation import ImmunizationRecommendation
from fhir.resources.medication import Medication
from fhir.resources.medicationadministration import MedicationAdministration
from fhir.resources.medicationdispense import MedicationDispense
from fhir.resources.medicationknowledge import MedicationKnowledge
from fhir.resources.medicationrequest import MedicationRequest
from fhir.resources.medicationstatement import MedicationStatement

# Clinical - Care Provision
from fhir.resources.careplan import CarePlan
from fhir.resources.careteam import CareTeam
from fhir.resources.goal import Goal
from fhir.resources.nutritionorder import NutritionOrder

# Note: RequestGroup resource not available in fhir.resources R4
from fhir.resources.riskassessment import RiskAssessment
from fhir.resources.servicerequest import ServiceRequest
from fhir.resources.visionprescription import VisionPrescription

# Clinical - Request & Response
from fhir.resources.communication import Communication
from fhir.resources.communicationrequest import CommunicationRequest
from fhir.resources.devicerequest import DeviceRequest
# Note: DeviceUseStatement was replaced by DeviceUsage in R5, not available in R4

# Base - Individuals
from fhir.resources.group import Group
from fhir.resources.patient import Patient
from fhir.resources.person import Person
from fhir.resources.practitioner import Practitioner
from fhir.resources.practitionerrole import PractitionerRole
from fhir.resources.relatedperson import RelatedPerson

# Base - Entities
from fhir.resources.biologicallyderivedproduct import BiologicallyDerivedProduct
from fhir.resources.device import Device
from fhir.resources.devicemetric import DeviceMetric
from fhir.resources.endpoint import Endpoint
from fhir.resources.healthcareservice import HealthcareService
from fhir.resources.location import Location
from fhir.resources.organization import Organization
from fhir.resources.organizationaffiliation import OrganizationAffiliation
from fhir.resources.substance import Substance

# Base - Management
from fhir.resources.encounter import Encounter
from fhir.resources.episodeofcare import EpisodeOfCare
from fhir.resources.flag import Flag
from fhir.resources.list import List as FHIRList

logger = logging.getLogger(__name__)


class ValidationReport(BaseModel):
    """Report generated by the Python FHIRValidator for a single extracted dict."""

    raw_dict: Dict[str, Any]
    status: str  # "VALID" or "INVALID"
    errors: List[str] = []
    resource: Optional[BaseModel] = None


class FHIRValidator:
    """AC4, Phase 5 AC1, Phase 6 AC3-AC4: Strict validation wrapper supporting all 55 clinical + base resources."""

    # Phase 6: Mapping of resourceType strings to their corresponding fhir.resources Pydantic models
    # All 55 Clinical and Base FHIR R4 Resources (alphabetically sorted)
    RESOURCE_MAP = {
        # Clinical - Summary
        "AdverseEvent": AdverseEvent,
        "AllergyIntolerance": AllergyIntolerance,
        "ClinicalImpression": ClinicalImpression,
        "Condition": Condition,
        "DetectedIssue": DetectedIssue,
        "FamilyMemberHistory": FamilyMemberHistory,
        "Procedure": Procedure,
        # Clinical - Diagnostics
        "BodyStructure": BodyStructure,
        "DiagnosticReport": DiagnosticReport,
        "ImagingStudy": ImagingStudy,
        # "Media": Media,  # Not available in fhir.resources R4
        "MolecularSequence": MolecularSequence,
        "Observation": Observation,
        "QuestionnaireResponse": QuestionnaireResponse,
        "Specimen": Specimen,
        # Clinical - Medications
        "Immunization": Immunization,
        "ImmunizationEvaluation": ImmunizationEvaluation,
        "ImmunizationRecommendation": ImmunizationRecommendation,
        "Medication": Medication,
        "MedicationAdministration": MedicationAdministration,
        "MedicationDispense": MedicationDispense,
        "MedicationKnowledge": MedicationKnowledge,
        "MedicationRequest": MedicationRequest,
        "MedicationStatement": MedicationStatement,
        # Clinical - Care Provision
        "CarePlan": CarePlan,
        "CareTeam": CareTeam,
        "Goal": Goal,
        "NutritionOrder": NutritionOrder,
        # "RequestGroup": RequestGroup,  # Not available in fhir.resources R4
        "RiskAssessment": RiskAssessment,
        "ServiceRequest": ServiceRequest,
        "VisionPrescription": VisionPrescription,
        # Clinical - Request & Response
        "Communication": Communication,
        "CommunicationRequest": CommunicationRequest,
        "DeviceRequest": DeviceRequest,
        # "DeviceUseStatement": DeviceUseStatement,  # Replaced by DeviceUsage in R5
        # Base - Individuals
        "Group": Group,
        "Patient": Patient,
        "Person": Person,
        "Practitioner": Practitioner,
        "PractitionerRole": PractitionerRole,
        "RelatedPerson": RelatedPerson,
        # Base - Entities
        "BiologicallyDerivedProduct": BiologicallyDerivedProduct,
        "Device": Device,
        "DeviceMetric": DeviceMetric,
        "Endpoint": Endpoint,
        "HealthcareService": HealthcareService,
        "Location": Location,
        "Organization": Organization,
        "OrganizationAffiliation": OrganizationAffiliation,
        "Substance": Substance,
        # Base - Management
        "Encounter": Encounter,
        "EpisodeOfCare": EpisodeOfCare,
        "Flag": Flag,
        "List": FHIRList,  # Note: renamed import to avoid conflict with Python's built-in list
    }

    def validate_bundle(self, resources: List[Dict[str, Any]]) -> List[BaseModel]:
        """Legacy method for returning only valid models. Uses evaluate_bundle underneath."""
        reports = self.evaluate_bundle(resources)
        return [
            r.resource
            for r in reports
            if r.status == "VALID" and r.resource is not None
        ]

    def evaluate_bundle(
        self, resources: List[Dict[str, Any]]
    ) -> List[ValidationReport]:
        """Phase 5 AC1: Iterates through raw LLM outputs and tags them as VALID/INVALID with error traces."""
        reports = []

        for item in resources:
            res_type = item.get("resourceType")

            if not res_type:
                reports.append(
                    ValidationReport(
                        raw_dict=item,
                        status="INVALID",
                        errors=["Missing 'resourceType' key."],
                    )
                )
                continue

            model_class = self.RESOURCE_MAP.get(res_type)
            if not model_class:
                msg = f"Resource type '{res_type}' is not currently supported by the Validator."
                reports.append(
                    ValidationReport(raw_dict=item, status="INVALID", errors=[msg])
                )
                continue

            try:
                # Attempt strict Pydantic instantiation
                valid_instance = model_class(**item)
                reports.append(
                    ValidationReport(
                        raw_dict=item, status="VALID", resource=valid_instance
                    )
                )
            except ValidationError as e:
                # Capture specific field errors from Pydantic
                error_list = [
                    f"{err['loc'][0]}: {err['msg']}"
                    for err in e.errors()
                    if "loc" in err and len(err["loc"]) > 0
                ]
                # If loc parsing fails, just dump the raw Pydantic errors
                if not error_list:
                    error_list = [str(err) for err in e.errors()]

                reports.append(
                    ValidationReport(raw_dict=item, status="INVALID", errors=error_list)
                )
            except Exception as e:
                reports.append(
                    ValidationReport(
                        raw_dict=item,
                        status="INVALID",
                        errors=[f"Unexpected error: {e}"],
                    )
                )

        return reports
