import logging
from typing import List, Dict, Any, Optional
from pydantic import ValidationError, BaseModel
from fhir.resources.patient import Patient
from fhir.resources.observation import Observation
from fhir.resources.condition import Condition
from fhir.resources.encounter import Encounter
from fhir.resources.medicationrequest import MedicationRequest
from fhir.resources.procedure import Procedure
from fhir.resources.allergyintolerance import AllergyIntolerance

logger = logging.getLogger(__name__)


class ValidationReport(BaseModel):
    """Report generated by the Python FHIRValidator for a single extracted dict."""

    raw_dict: Dict[str, Any]
    status: str  # "VALID" or "INVALID"
    errors: List[str] = []
    resource: Optional[BaseModel] = None


class FHIRValidator:
    """AC4, Phase 5 AC1: Strict validation wrapper that generates detailed reports."""

    # Mapping of resourceType strings to their corresponding fhir.resources Pydantic models
    RESOURCE_MAP = {
        "Patient": Patient,
        "Observation": Observation,
        "Condition": Condition,
        "Encounter": Encounter,
        "MedicationRequest": MedicationRequest,
        "Procedure": Procedure,
        "AllergyIntolerance": AllergyIntolerance,
    }

    def validate_bundle(self, resources: List[Dict[str, Any]]) -> List[BaseModel]:
        """Legacy method for returning only valid models. Uses evaluate_bundle underneath."""
        reports = self.evaluate_bundle(resources)
        return [
            r.resource
            for r in reports
            if r.status == "VALID" and r.resource is not None
        ]

    def evaluate_bundle(
        self, resources: List[Dict[str, Any]]
    ) -> List[ValidationReport]:
        """Phase 5 AC1: Iterates through raw LLM outputs and tags them as VALID/INVALID with error traces."""
        reports = []

        for item in resources:
            res_type = item.get("resourceType")

            if not res_type:
                reports.append(
                    ValidationReport(
                        raw_dict=item,
                        status="INVALID",
                        errors=["Missing 'resourceType' key."],
                    )
                )
                continue

            model_class = self.RESOURCE_MAP.get(res_type)
            if not model_class:
                msg = f"Resource type '{res_type}' is not currently supported by the Validator."
                reports.append(
                    ValidationReport(raw_dict=item, status="INVALID", errors=[msg])
                )
                continue

            try:
                # Attempt strict Pydantic instantiation
                valid_instance = model_class(**item)
                reports.append(
                    ValidationReport(
                        raw_dict=item, status="VALID", resource=valid_instance
                    )
                )
            except ValidationError as e:
                # Capture specific field errors from Pydantic
                error_list = [
                    f"{err['loc'][0]}: {err['msg']}"
                    for err in e.errors()
                    if "loc" in err and len(err["loc"]) > 0
                ]
                # If loc parsing fails, just dump the raw Pydantic errors
                if not error_list:
                    error_list = [str(err) for err in e.errors()]

                reports.append(
                    ValidationReport(raw_dict=item, status="INVALID", errors=error_list)
                )
            except Exception as e:
                reports.append(
                    ValidationReport(
                        raw_dict=item,
                        status="INVALID",
                        errors=[f"Unexpected error: {e}"],
                    )
                )

        return reports
